FROM lsiobase/ubuntu:jammy
COPY qemu-aarch64-static /usr/bin/

ARG DEBIAN_FRONTEND=noninteractive

ENV \
	HOME=/config \
	TZ=UTC

RUN \
	echo "**** install packages ****" && \
	apt-get update && \
	apt-get install -y --no-install-recommends \
		fcgiwrap nut-cgi && \
	echo "**** clean up ****" && \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*

COPY root /

VOLUME ["/config/www/nut"]
