#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    HOME=${HOME}"
    echo "    PUID=${PUID}"
    echo "    PGID=${PGID}"
    echo "    TZ=${TZ}"
}

print_vars

echo "*** fix /etc/nut/upsset.conf ***"
sed -i '/I_HAVE_SECURED_MY_CGI_DIRECTORY/s/^### //' /etc/nut/upsset.conf

# Copy HTML files where the web server container can see them
mkdir -p /config/www/nut && cp -p /usr/share/nut/www/* /config/www/nut
chown -R abc:abc /config/www/nut
