name: Build and Push

on:
  push:
    branches: ["**"]
  pull_request:
  schedule:
    - cron: '0 10 * * 0'
  workflow_dispatch:

jobs:
  build:
    uses: jchonig/workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: nut-cgi
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  keepalive:
    if: github.event_name == 'schedule'
    uses: jchonig/workflows/.github/workflows/keepalive.yml@main
    permissions:
      actions: write
